### ISSUE TITLE
OID Referenzierung als Datenbtyp 

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#1]
**Klasse Asset.ID_GUID:**
``` ...
/** Technische ID zur Identifikation der einzelnen Asset-Objekte. Diese ID ist nicht für die Kommunikation vorgesehen!
       */
      ID_GUID : MANDATORY OID URI;
...
```
Frage. wie kann ich korrekt deklarieren, dass das Attribut `ID_GUID` vom Typ OID, so wie im TPOIC  `CoreGeolAsset` defineirt, handelt?

**Comment by signedav** [comment]
Wie meinst du "so wie im TOPIC `CoreGeolAsset` definiert"? 

Wenn du im Topic die OID als UUID definiert hast:
```
  TOPIC CoreGeolAsset =
    OID AS INTERLIS.UUIDOID;
```
werden UUIDs (GUIDs) generiert für die technischen Ids für alle Klassen. 

Wenn es nur um Asset gehen soll, dann so:
```
       CLASS Asset =
          OID AS INTERLIS.UUIDOID;
```

Oder geht es darum, dass du den Wert spezifisch in einem Attribut ID_GUID hast?

**Comment by oesterli** [comment]
Im TOPIC habe ich `OID A INTERLIS.UUIDOID` definiert.
Für mich bedeutet das, dass ich jetzt den Datentyp OID zur Verfügung habe und diesen einem Attribut in einer beliebigen Klasse zuweisen kann, z.B. für das Attribut ID_GUID in der Klasse Asset. Kann ich das so wie hier machen?: `ID_GUID : MANDATORY OID;`? 

Über den UML-Editor hatte ich es wie oben beschrieben gemacht `ID_GUID : MANDATORY OID URI;`, aber dort steht noch das `URI` als Datentyp neben dem `OID`.

Oder wird mit der Definition der OID im Topic automatisch, eine OID pro Klasse definiert, ohne, dass man das konkret nochmal definieren muss?

**Comment by signedav** [comment]
Die OID auf dem TOPIC spezifiziert, bedeutet, dass dieser Typ als OID für alle Klassen angewendet wird. Wenn es nur in einer Klasse spezifiziert wird, wird es nur für diese Klasse angwendet.

Bei einer physikalischen Umsetzung wird dann meistens diese ID mit einem generierten Wert abgefüllt bei der Erstellung eines Eintrages. 
Zbs. PostgreSQL: 
```
t_ili_tid uuid DEFAULT uuid_generate_v4()
```
Im Geopackage kann es aber nicht im Backend abgefüllt werden, deshalb erstellt der Model Baker im Projekt einen Default Wert:
```
substr(uuid(), 2, 36)
```

**Comment by signedav** [comment]
Aber ich denke, das ist gar nicht was du willst. Du möchtest diese Funktionalität für ein Attribut `ID_GUID` haben, richtig?

**Comment by oesterli** [comment]
resolved

OID wurde, wie beschrieben im TOPIC deklariert
