### ISSUE TITLE
Kardinalitäten von Attributen

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#10]
@signedav 
Wie kann man im INTERLIS-Code darstellen, dass ein Attribut {1..*} oder {0..*} auftritt.
Dass Keyword `MANDATORY` sagt doch nur, dass dass Attribut genau 1 mal vorkommenb muss.

**Comment by signedav** [comment]
Hast du ein konkretes Beispiel dazu?

**Comment by oesterli** [comment]
Z.B. in der Klasse `Asset`   
 
`      !! Identifikator(en) (ID) des Asset. Wenn möglich soll die Original-ID verwendet werden.  
      ID_Alternate : TEXT*50; 

Hier wollen wir die Möglichkeit haben mehrere ID erfassen zu können.

`

**Comment by oesterli** [comment]
Muss man dafür eine `BAG OF` nutzen?

**Comment by signedav** [comment]
Ja genau. Um mehrere Objekte im Attribut zu speichern brauchst du `BAG OF`, `LIST OF` oder eine Association (wenn die Children Klassenobjekte sind). Wobei in deinem Fall wärs `BAG OF`.

**Comment by oesterli** [comment]
Ok. Das heisst dann aber auch, dass ich eine `STRUCUTRE` für das jeweilige Attribut in der `DOMAIN` erstellen muss.

**Comment by oesterli** [comment]
Ich hab's übernommen. und schliesse das Issues damit.

**Comment by oesterli** [comment]
Ich hab's wieder geöffnet. :-)

Muss ein `LIST OF` nutzen, wenn ich mehrere Werte aus einer `ENUMERATION` verwenden will?
z:B.: Klasse `Asset`, Attribut `TOPIC `

Muss dann die `ENUMERATION `auch in der `DOMAIN` definiert sein?

**Comment by signedav** [comment]
Ich würde `BAG OF` verwenden, wenn du nicht auf eine Reihenfolge angewiesen bist.
Und wenn wir die STRUCTURE im DOMAIN definieren, dann müssen wir auch die ENUMS dort definieren, denn dort kann man keine Definitionen des TOPICS verwenden (nur umgekehrt).

**Comment by oesterli** [comment]
Entfällt nach Codelist integration
