### ISSUE TITLE
MimeTypes definieren

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#11]
@signedav 
Wir hatten bei einer unserer ersten Besprechungen gssagt, dass wir für Asset.Format MimeTypes definieren.

Wie können wir das machen?

**Comment by signedav** [comment]
Wenn möglich verwenden wir bestehende MimeTypes. Wo dies nicht möglich ist, machen wir unsere eigenen. Dies ist von Vorteil, wenn zBs. mal eine custom Application darauf aufbauen möchte.

MimeTypes haben ein Format von `Typ "/" [Baum "."] Subtyp ["+" Suffix] *[";" Parameter]` Ziemlich gut beschrieben hier https://de.wikipedia.org/wiki/Internet_Media_Type

Ich würde sagen wir gehen folgendermassen vor:
- Sammeln aller Typen, die wir brauchen
- Wenn keine "offiziellen" MimeTypes vorhanden sind, recherchieren ob irgendwelche Custom-Types verwendet werden dafür (irgendwo bei jemandem sonst) und ob diese Sinn machen
- Ansonsten erstellen von eigenen MimeTypes

Können wir dazu mal eine Liste machen, was wir brauchen?

**Comment by signedav** [comment]
```
      Format : MANDATORY (
        !! Weitere, nicht genannte Formate
        other,
        !! Analoge Dokumente (Papier, Mikrofichen etc.)
        textAnalog,
        !! Grafisch analoge Zeichnung
        graphicAnalog,
        !! Grafisch digitale Vektorgrafik
        GraphicVector,
        !! Grafisch digitale Rastergrafik
        GraphicRaster,
        !! Sammlung von einzelnen Assets, z.B. Rohdaten einer Seismikkampagne
        Package,
        !! Digitales binäres Format
        Binaer,
        !! Textformat (z.B.: ascii, txt, doc, docx, xls, xlsx, xml, csv etc.)
        textDigital,
        !! Seismikspezifische Formate (SPS, SEG2, SEGD, SEGY etc.)
        Seismic(
          SEGY,
          SEGY_exported,
          !! andere seismikspezifische Formate
          other
        ),
        !! PDF-Datei
        PDF,
        !! ESRI Shapefile
        SHP,
        !! Log-Files (Log ASCII Standard)
        LAS
      );
```

**Comment by oesterli** [comment]
@signedav 
Für das SEG-Y-Format habe ich noch folgende Links gefunden.

![image](https://user-images.githubusercontent.com/34167552/130361331-4e476ae3-71fa-4c84-b3ca-41c1726e3e41.png)
![image](https://user-images.githubusercontent.com/34167552/130361343-5b495d3d-bccc-4bf3-8431-cdbcf67e2dba.png)

Ich weiss aber nicht, welche Definition besser ist

Ein wichitges Format ist LAS (Log ASCII Standard), dafür habe ich keine MIME-TYpoe-Definition gefunden, aber hier die Spezifikation
 
![image](https://user-images.githubusercontent.com/34167552/130361391-d019497a-54b6-4799-a45d-2b6c0905b778.png)

**Comment by signedav** [comment]
Falls wir einen der oben genannten Mimetype nehmen, wäre ich für den ersteren. Währenddem `application/seismic-segy` in einem Projekt von [OGC](https://www.ogc.org/) verwendet wird und `application/segy` für den [Apache Lucerne ](https://lucene.apache.org/)Parser, denke ich sind wir eher im Kontext des ersteren unterwegs. Zudem müssen wir ja auch zwischen `SEGY` und `SEGY_exported` unterscheiden.

Noch eine Frage: analoge Texte und Graphiken existieren nicht Digital?

**Comment by signedav** [comment]
Wollte mal eine Tabelle erstellten, doch bin gerade etwas unsicher.
1. Enthalten die offiziell registrierten "custom" Mimetypes den Prefix `vnd.` (für den Vendor), intern/privat verwendete sollen mit dem Prefix `x-` auskommen. Doch irgendwie sind wir hier weder noch. Ich muss mich also noch schlau machen, ob wir Prefixen verwenden sollen oder nicht, aber erst wenn klar ist ob...
2. Wir wirklich in diese Richtung gehen sollen? Denn Typen wie zBs. `Textformat (z.B.: ascii, txt, doc, docx, xls, xlsx, xml, csv etc.)` kann man nicht gut mit einem einzigen Mimetype beschreiben. Da gäbe es einen für jeden Dateityp. Ausserdem `analoge Texte` und `analoge Graphiken` - was sind das für Dateien? Eben keine Dateien? Natürlich können wir definieren, was wir wollen, aber ich denke das Level sollte schon gleich sein. Wenn PDF korrekt `application/pdf` als Mimetype hat, wär auch schön hätte ein DOC korrekt `application/ms-word` etc.
Anyway hier noch die Tabelle, die ich begonnen hab.

| Format        | Mimetype           | Registred  |
| ------------- |:-------------:| -----:|
| other | ??? | yes |
|  textAnalog | ??? | yes |
|  graphicAnalog | ??? | yes |
|  GraphicVector | image/svg+xml | yes |
|  GraphicRaster | image/png image/jpeg ...| yes |
|  Package | multipart/mixed | yes |
|  Binaer | ??? | yes |
|  textDigital | application/msword, text/plain, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel  ... |    yes |
|  Seismic SEGY | application/seismic-SEGY  |  no |
|  Seismic SEGY_exported | application/seismic-SEGY-exp | no |
|  Seismic other | application/seismic-SEGY-exp  |   no |,
|  PDF | application/pdf |  yes |
|  SHP | application/vnd.shp |  yes |
|  LAS | text/las |   no |

**Comment by signedav** [comment]
Nach Telefongespräch denken wir, dass wir vermutlich keine Mime-Types verwenden, da es nicht analog zu den benutzten Typen angewendet werden kann.
