### ISSUE TITLE
Questions and todos

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#14]
**Klasse Asset:**
ID_SGS darf nicht `MANDATORY` sein oder es muss ein `CONSTRAINT` erstellt werden.

**Beziehung AssetMain - AssetPart:**
So wie es jetzt modelliert ist `AssetMain -- {1} Asset` kann kein Asset erstellt werden, da man bei der Eingabe der Daten eines Assets immer schon ein AssetMain zuweisen muss. - > Lösung: Komposition  oder `AssetMain -- {0..1} Asset` oder `Abhängigkeit`?

**Klasse AssetAdmin:**
- `CONSTRAINT` einfügen, der sicherstellt, dass OCR_Quality ausgefüllt ist, wenn OCR = true  
      `MANDATORY CONSTRAINT  
        OCR <> True OR DEFINED (OCR_Quality);`
- `Relative_Path` umbenennen in `Relative_Path_Admin`, da es den Pfad zum Einwilligungsformular oder Vertrag etc. abbildet

**Comment by signedav** [comment]
> Beziehung AssetMain - AssetPart:
So wie es jetzt modelliert ist AssetMain -- {1} Asset kann kein Asset erstellt werden, da man bei der Eingabe der Daten eines Assets immer schon ein AssetMain zuweisen muss. - > Lösung Komposition? oder AssetMain -- {0..1} Asset?

Ja, das muss 0..1 sein, denn der Asset muss ja nicht auf ein Main-Asset referenzieren (wenn er selbst einer ist). Bin gerade nicht sicher ob man eine "freiwillige" Komposition machen kann. also so etwas: `AssetMain -<#> {0..1} Asset`
Ist ja eigentlich dann nicht mehr als Komposition erlaubt, denn dort darf ein Child nicht ohne Parent existieren. Selbst wenn es bei uns Sinn macht und in Interlis erlaubt sein könnte, würde ich dies eher nicht machen, da Umsetzungen bei einer Komposition unter Umständen das Anlegen eines Childs ohne Parent verhindern.
