### ISSUE TITLE
Definition Codelisten

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#2]
Wie werden die externen Codelisten modelliert.

Bisher sind bei verschiedenen Attributen wertelisten als Enumeration "hart" im Modell codiert. wie können diese aus gelagert werden?

**Comment by oesterli** [comment]
@signedav 
Können wir heute oder in den nächsten Tagen die Definition der Codelisten ansehen. Ich könnte das dann direkt in den neuen Branch einbauen.

**Comment by signedav** [comment]
Wär Donnerstagmorgen auch möglich?

**Comment by oesterli** [comment]
Mir würde Donnerstagnachmittag ab 16 Uhr besser passen. Am Vormittag geht's nur zwischen 9 und10:30 Uhr

**Comment by signedav** [comment]
Ok. 16.00 ist perfekt

**Comment by oesterli** [comment]
TO DO:
Codelisten für DM_Asset aufbauen

**Comment by signedav** [comment]
Betreffend den TIDs. Das Verhalten ist so:
Beim erstellen der Einträge wird die `t_id` (DB Intern) gesetzt, die `t_ili_tid` bleibt leer. Beim Export werden dann die `t_id` in die `TID` des XML Elements geschrieben. Beim erneuten Import werden die `t_id` (DB Intern) neu generiert, im `t_ili_tid` stehen jetzt die "alten" `t_id` aus dem XML. Was wir gestern beobachtet haben ist, dass wenn wir es jetzt exportieren, wieder die `t_id` in die XML geschrieben werden und die `TID` sich somit verändert.

Diese Problematik tritt nicht auf, wenn wir die `t_ili_tid` von Anfang an nutzen. Also wenn wir zum Beispiel UUIDs verwenden:
```
  TOPIC Catalogues =
    OID AS INTERLIS.UUIDOID;
```

Hier bleiben die Ids von Anfang an stabil. Ich sehe, dass auch beim Katalogmodell von Glarus UUIDs verwendet werden, also ist das nicht so verkehrt. Der Export sieht dann so aus:
```
<DMGeolAssets.Catalogues.PurposeItem TID="13341d36-c211-4ca5-92a8-1d93b06a7faa"><IsSuperItem>true</IsSuperItem><IsUseable>false</IsUseable><Name>geology</Name></DMGeolAssets.Catalogues.PurposeItem>
<DMGeolAssets.Catalogues.PurposeItem TID="fe96874c-eef1-4376-a9aa-42aa3325e23e"><IsSuperItem>false</IsSuperItem><IsUseable>true</IsUseable><Parent REF="13341d36-c211-4ca5-92a8-1d93b06a7faa"></Parent><Name>geol chil1</Name></DMGeolAssets.Catalogues.PurposeItem>
<DMGeolAssets.Catalogues.PurposeItem TID="fc655d3c-60da-4f81-aae8-37ad5afed23b"><IsSuperItem>false</IsSuperItem><IsUseable>true</IsUseable><Parent REF="13341d36-c211-4ca5-92a8-1d93b06a7faa"></Parent><Name>geol child 2</Name></DMGeolAssets.Catalogues.PurposeItem>
```

Weshalb in unserem Use Case nicht einfach die `t_ili_tid` verwendet wird ab dann wo sie verfügbar ist, weiss ich nicht. Es ist aber für unsere Arbeit hier gerade nicht relevant. Finde ich es doch heraus, werde ich dich updaten.

**Comment by signedav** [comment]
Übrigens noch zur Info. Ein Use Case, wo man die "Zwischentabelle" `CatalogueReference` verwendet ist, wenn man darauf Attribute setzt. Beispielsweise:
```
    CLASS PurposeItem EXTENDS CatalogueObjects_V1.Catalogues.Item =
      Name : MANDATORY TEXT;
      Description : TEXT;
    END PurposeItem;
    
    STRUCTURE PurposeRef EXTENDS CatalogueObjects_V1.Catalogues.CatalogueReference =
      Reference (EXTENDED) : REFERENCE TO (EXTERNAL) PurposeItem;
      Reason : TEXT;
    END PurposeRef;
```

**Comment by oesterli** [comment]
@signedav 
Könntest Du mir nochmal sagen, wie Du im QGIS/ModelBaker die Domain-Tabelle editierbar machen kannst?

**Comment by signedav** [comment]
Entweder du erstellst einen neuen Layer mit derselben Source. Das habe ich gestern gemacht. Dabei verlierst du aber die Konfiguration, die der Modelbaker auf dem Layer gemacht hat.

Alternativ könntest du auch das Projekt abspeichern als "*.qgs" File (anstelle qgz), dann dieses mit einem Texteditor öffnen und dort drin nach dem Layer suchen und `readOnly=1` auf 0 setzen.
```
<maplayer autoRefreshTime="0" geometry="No geometry" wkbType="NoGeometry" maxScale="0" autoRefreshEnabled="0" styleCategories="AllStyleCategories" minScale="1e+08" type="vector" readOnly="1" refreshOnNotifyEnabled="0" refreshOnNotifyMessage="" hasScaleBasedVisibilityFlag="0">
```

**Comment by oesterli** [comment]
Super, Danke! Hat geklappt.

**Comment by oesterli** [comment]
@signedav 
Wie kann ich einen CONSTRAINT auf einen Wert aus der einer Codelist erstellen.

Bis her hatte im Attribut 'Asset.Kind' den folgenden CONTRAINT.
```
MANDATORY CONSTRAINT
        Kind <> #report OR DEFINED (TitlePublic);
```
Das funktioniert mit den externen Codelists jetzt nicht mehr. wie muss ich den wert `#report` definieren, damit der CONSTRINT funktioniert?

**Comment by signedav** [comment]
Das ist eine gute Frage. Ich werde dies mal abklären.
Wäre ja sehr unschön, müsste man auf Identifier überprüfen. So:
```
MANDATORY CONSTRAINT
        Material <> #550e8400-e29b-11d4-a716-446655440000 OR DEFINED (MetallAnteilInProzent);
```
Da würde ich dann eher auf Enumerations zurückgehen.

**Comment by signedav** [comment]
Die Lösung ist ein Referenzpfad:
```
MANDATORY CONSTRAINT
  Kind->Reference->Name==”report” OR DEFINED (TitlePublic);
```

Siehe auch dieses Model (vielleicht kennst du es sogar) Hier wird es oft so gemacht:
http://models.geo.admin.ch/Swisstopo/DM_Geology_V2_1.ili

**Comment by oesterli** [comment]
@signedav 
Ich habe versucht den CONSTRAINT so einzubauen. Ich bekomme aber den folgenden fehler:
`M:\Appl\DATA\PROD\lg\01_PRODUKTION\Datenmodell\34-Unterstuetzung_tech_Modellierung\DM-Asset\work\dmAssets\scr\DM_Asset.ili:344:incompatible datatypes
--- compiler run failed 22.08.21 16:43`

kannst Du dir das mal ansehen. Ich push das ganze heute noch ins github.

**Comment by signedav** [comment]
Können wir den schliessen?

**Comment by oesterli** [comment]
Abgeschlossen
