### ISSUE TITLE
Bemerkungen & Offene Fragen

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#3]
Bei unsere letzte Besprechung sind folgende Fragen offen geblieben:

**Klasse «Asset», Attribut «Path»**  
Dieses Attribut bildet den Pfad zum File des jeweiligen Assets auf unserem Filesystem ab.
 
-	**Frage:** Existiert zu einem Asset nur ein File oder können auch mehrere vorliegen? Wenn ja, wie grenzen sich die weiteren Files von eigenständigen Assets ab bzw. den AdditionalData ab?  
**Antwort:** Zu einem Asset können beliebig viele Daten (Files gehören). Aus unserer Sicht gehört zu einem Asset mindestens 1 File oder Datenpaket (z.B. im zip-Format). Zusätzlich scheint es uns sinnvoll wenn man die Möglichkeit hat Teile des Assets (Extrakte von aus einem PDF oder einzelne Files aus eine Datenpaket) separat mit dem Asset verknüpfen zu können.  Ich stelle mir daher vor eine zusätzliche Klasse AssetPart einzuführen, mit der die Teile eines Assets beschrieben werden können. damit könnte vermieden werden, dass für jeden Teile eines Assets als eigenes Asset definiert werden muss. Oder könnte die beschriebene Situation besser durch die bestehende rekursive Beziehung beschrieben werden? 
-	**Frage:** Wie gehen wir mit den extrahierten Teilen aus eine Dokument, z.B. Bohrprofilen, Karten etc. um? 
**Antwort:** siehe Antwort oben 
-	Sind die extrahierten Teile AdditionalData oder eigenständige Assets, die über die rekursive Beziehung mit dem «Mutter»-Asset verbunden werden?  
**Antwort:** siehe Antwort oben
-	**Frage:** Soll das Attribut «Path» nur den Pfad zu unserer internen Ablage beinhalten oder können auch Daten auf einem externen Speicher, z.B. auf einer Website, liegen?  
-**Antwort:** wir können uns auch vorstellen, dass die Files oder Datenpakete irgendwo im Web liegen. Ich könnte mir vorstellen, das wir ein Attribut "relativPath"mit Kardinalität {1} haben, dass den Pfad zum File/Datenpaket auf unserer internen Ablage abbildet. Dieses Atttibut ist auch nicht für den Datenaustausch gedacht. Zusätzlich führen wir eine Attributen "dataPath" mit Kardinalität{0..*} ein, dass Pfade zu beliebigen Ablagen (z.B. auf eine FTP-Server) abbildet. Für den Datentransfer könnte damit der Pfad zu den Daten gespeichert werden von dem die Daten heruntergeladen und dann ins Zielsystem integriert werden können.  

**Klasse «RegionOfInterst» (ROI) und Unterklassen «StudyLocation», «StudySection» und «StudyArea»**
Die Geometrien können in den folgenden Varianten abgebildet werden.
1) Eine ROI pro (Mulit-)Geometrie, z.B. Zu einem Asset besteht 1 ROI mit 3 Punkten «im Westen»; 1 ROI mit 2 Punkten «im Norden»; 1 ROI mit 1 Linie «im Norden», etc.
2) Eine ROI für ein Gebiet, z.B. 1 ROI mit 3 Punkten im Westen und 1 ROI «im Norden» mit 2 Punkten und 1 Linie

**Frage:** Welche Variante ist für uns die geeignete? Aus meiner Sicht deckt Variante 2 am ehesten unserer Bedürfnisse ab, oder?    
**Antwort** Variante 2 bildet unser bedürfnis am besten ab. Allerdings scheint es uns sinnvoll die Beziehung Asset-ROI so anzupassen, dass jede ROI nur zu einem Asset gehören kann.

**Comment by signedav** [comment]
### Assets und Dokumente
So wie ich das verstehe soll also ein Asset 1..* Dokumente enthalten. Allerdings soll die Klasse Asset genau ein Dokument enthalten, das mit `relativePath` verlinkt wird und alle weiteren sollen über die AssetParts hinzukommen. Diese AssetParts enthalten genau ein Dokument, das mit `relativePath` verlinkt wird. Richtig?

Unabhängig davon soll auf 0..* Web-Ressourcen verwiesen werden können. Richtig?

### Assets und Geometrien
So wie hier beschrieben soll eine ROI 1..* Geometrien verschiedener Typen enthalten. Im Gespräch heute habe ich aber erfahren, dass es sich nur um ein Geometrietyp pro ROI handelt. Allerdings soll ausgewählt werden können, um welchen es sich handelt. Also hat eine ROI entweder Punkt(e), Linie(n) oder Polygon(e).

Ein Asset soll nur eine ROI haben. Allerdings jeder AssetPart soll ebenfalls genau ein ROI haben. Oder sind Assets / AssetParts ohne ROI erlaubt? Ist ein Dokument-Link immer mit einer Geometrie verknüpft (über AssetPart bzw. Asset)?

### Asset und AssetPart
Soll ein Asset ein erweiterter AssetPart sein? Was enthält ein Asset genau, was ein AssetPart nicht enthält?

**Comment by oesterli** [comment]
**Assets und Dokumente**
Hat sich geklärt. Wir verwenden ein Attribut `RelativePath` für die Abbildung des relativen Pfads auf dem zukünftigen Haltungssystem (Fileablage). Zusätzlich definieren wir ein Attribut `URL` mit dem der Pfad zu einer Online Ressource (das gleiche File wie in RelativePath) abgebildet wird.

**Asset und AssetPart**
- Einführung des Klasse `AssetPackage` mit der ein gesamtes Datenpaket (kann mehrere Assets enthalten) abgebildet wird.
- AssetParts werden neu mit einer rekursiven Beziehung zwischen Asset-Asset abgebildet.
-

**Comment by oesterli** [comment]
Assets und Dokumente resolved
Assets und AssetPart resolved
Asset und Geometrie siehe Issue #6
