### ISSUE TITLE
OID als Attibut

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#35]
@signedav 
Wir haben jetzt über das Konstrukt 

`  TOPIC CoreGeolAsset =
    OID AS INTERLIS.UUIDOID;`  
für jedes Objekt einer Klasse eine OID definiert. diese wird dann bei der Erstellung des Objekt durf ili2db generiert.

Für die Objekte der Klassen `AsstItem` und `AssetPackage` möchten wir eine eindeutige ID haben, die auch im UML sichtbar ist. Diese ID soll eine Objektkennung und nicht nur eine "technische ID". Sie soll nach Möglichkeit auch zwischen Menschen ausgetauscht bzw. kommuniziert werden können, z.B. "Ich möchste das Asset mit der ID xyz anzeigen.

Kann man die OID dafür einem Attribut (z.B. mit dem Namen `AssetID`) zuweisen?  
Zum Beispiel mit: `... AssetID : MANDATORY INTERLIS.UUIDOID; ...`

**Comment by signedav** [comment]
Mit der Definition `AssetID : MANDATORY INTERLIS.UUIDOID;` wird spezifiziert, dass AssetID vom Typ `uuid` ist, es wird aber nicht bei der Erfassung eine UUID generiert. Ich denke, das geht ins gleiche Thema wie die Defaultwerte #34 Mit einem Meta-Attribut hätten wir dann hier irgendwie `!!@defaultValueExpression="uuid()"` (oder so).
