### ISSUE TITLE
Catalogue von einfacher Aufzählung in hierarchische Gliederung ändern

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#36]
@signedav 

Ich habe im DM_Catalogues für eine Wertelisten einen "einfachen" ohne hierarchische Gliederung erstellt.
Jetzt habe bemerkt, dass ich doch einen hierarchischen Katalog benötige.

Wie kann ich die einfache Struktur in eine hierarchische umwandeln ohne, dass ich die bereits erfassten Werte verliere?
Muss ich dazu am besten das DM_Catalogues auf hierarchisch anpassen und dann das XTF auf die gleiche Weise anpassen? Oder gibt ein einen einfacheren Weg?

**Comment by signedav** [comment]
Vielleicht - da bin ich jetzt aber nicht sicher - kannst du auch das XTF in die hirarchische Struktur importieren ohne anzupassen, musst du aber ausprobieren.
