### ISSUE TITLE
Catalogue-werte aus Exceltabelle übernehmen 

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#37]
@signedav 

Für das DM_Catalogues habe ich sämtliche Werte über Model Baker erfasst. Die Werte habe ich aber nur auf Deutsch übersetzt.
Meine Kollegin Sabine hat bereits eine grössere Anzahl von Werten, insbesondere für zukünftige Kataloge in einem Excel in verschiedenen Sprachen erfasst.

Damit ich nicht alle Werte wieder neu eintippen muss, würde ich gerne die Werte aus der Exceltabelle via QGIS in die Datenbank aufnehmen.
Wie gehe diesbezüglich am besten vor? Kann ich die Exceltabelle (oder ein anderes Format, z.B. csv) mit eine Join an die jeweilige Attributtabelle im QGIS anhängen?

**Comment by signedav** [comment]
Ja, du kannst das mit QGIS machen. Ich würde das CSV als Layer in QGIS ziehen, dann in den Tabellen der Codeliste mit dem Feldrechner auf die CSV Layer zugreifen. Kann dir das auch in einer Session zeigen.
