### ISSUE TITLE
Admin-Klassen in separatem Topic?

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#38]
@signedav 

Ich habe mir die Frage gestellt, ob es nicht sinnvoll wäre die `Admin`-Klassen in einem separatem Topic zu modellieren. Für den Datenaustausch sind sich weniger relevant und sie bilden grosstenteils unsere Bedürfnisse ab.
Würde das den Datenaustauch nicht vereinfachen?

**Comment by signedav** [comment]
Oder in einem separaten Modell? Also ein Modell ohne Admin Klassen und dann ein zweites, das auf dem ersten aufbaut und dieses um die Admin Klassen erweitert?

**Comment by oesterli** [comment]
@signedav 
Je länger ich es mir überlege, desto mehr tendiere ich zu einem getrennten Admin-Modell.
