### ISSUE TITLE
Objektkatalog

### ISSUE THREAD

**Issue by moojoel** [oesterli/dmAssets#40]
A.) Es gibt noch Tippfehler im Objektkatalog
B.) Mir ist teilweise nicht klar, was die einzelnen Begriffe bedeuten (z.B. Unterschied zwischen Label undifferenziert und unknown)
C.) Können die Einträge im Objektkalalog später ergänzt bzw. verändert werden? Ich bin mir nicht sicher ob Formate vollständig ist z.B. sind die Seismik Sachen mit Robin abgesprochen?, ManCatLabels und Kind: Für mich ist da noch etwas ein durcheinander. Können alle Kombis so vorkommen?

**Comment by sabinebrodhag** [comment]
siehe auch Issue #41

**Comment by oesterli** [comment]
@sabinebrodhag @moojoel 
Ich würde vorschlagen, dass wir die Punkte zusammen ansehen und die offenen Punkte klären.
