### ISSUE TITLE
Beschreibung der Attribute

### ISSUE THREAD

**Issue by moojoel** [oesterli/dmAssets#41]
Mir fehlt teilweise der Zusammenhang.
Gibt es irgendwo eine Beschreibung, was die einzelnen Attribute bedeuten und für was und wie sie genau angewendet werden sollen/können? Mir scheint als gäbe es da für den jeweiligen Erfasser relativ viel Speilraum. Dies würde ich unbedingt vermeiden, damit die erfassten Dokumente Assets so einheitlich wie möglich erfasst sind.
M.E. braucht es da zusätlich eine beschreibende Liste für jedes Attribut.

**Comment by oesterli** [comment]
@sabinebrodhag
Mein Ziel ist, dass das DM und die komplette Doku nur noch auf dem Github liegt.
Dazu möchte ich ein swistopo- oder LG-github aufbauen, so wie das geoadmin-github auf dem die swissforages-repos liegen. wir erstellen dann pro DM ein eigenes Repo und können so die Entwicklung aber auch Aktualisierungen, z.B. neue Releases, dokumentieren. 
Am Ende gibt es dann nur noch das github und das https://models.geo.admin.ch/
