### ISSUE TITLE
Geometrien

### ISSUE THREAD

**Issue by moojoel** [oesterli/dmAssets#42]
Können auch 3D Geometrien aufgenommen werden? , z.B. Bohrpfade, Kuben z.B. für die Ausdehung von  3D-Modellen inkl. Tiefe, Slices (Profile, oder Tiefe der 2D Seismik.

**Comment by oesterli** [comment]
@sabinebrodhag @moojoel 
Ich bin der Meinung von Sabine. Bisher ist das DM-Asset auf 2D ausgerichtet. Für stellt sich auch die Frage, ob wir Metadaten im 3D-Raum benötigen. wir haben nicht so viele Daten, die sich in der Z-Richtung überlagern
