### ISSUE TITLE
Think about Association Strength

### ISSUE THREAD

**Issue by signedav** [oesterli/dmAssets#45]
Maybe here https://github.com/oesterli/dmAssets/blob/main/scr/DM_Asset.ili#L423

## Here some notes
- Association `--`: Relationship between independent objects. 
- Aggregation `-<>`: Relationship between parts and a whole. A part can be part of multiple wholes.
- Composition `-<#>`: Relationship between parts and a whole. A part can only be part of a single whole.

Association: The objects concerned are loosely connected. Like Books and Writers. If one of the objects is copied, the copy is connected to the same objects as the original. If an object is deleted, the relationship is deleted at the same time, however the object itself remains.

Aggregation: There is only a feeble relationship between the entirety and its parts. As opposed to associations, when making a copy of the entirety corresponding copies of the parts are established. On deletion of the whole, the parts persist. It's like a team and its members. However since INTERLIS 2 Aggregations are handled same as Associations (not sure about that last stat ement)

Composition: A strong relationship exists between the entirety and its parts. Only one entirety may be assigned to a certain part-object. When deleting the entirety its parts are likewise deleted. Like flat and its rooms.

**Comment by oesterli** [comment]
wie Do. 18.11. besprochen.
Wird nur die Beziehung zwischen GeometryOfInterest und AssetBase in eine Komposition umgewandel

GeometryOfInterest --<#>AssetBase

**Comment by oesterli** [comment]
Composition AssetBase <#>- GeometryOfInterest integreated
