### ISSUE TITLE
Enumerations durch Codelists ersetzen

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#46]
**DM_Asset.ili**  
Zeile 55: STRUCTURE LegalDoc:  `Type : MANDATORY (`    
Zeile 115: CLASS AdminAssetBase (ABSTRACT): `NationalRelevance : MANDATORY (`  
Zeile 174: CLASS AdminAssetItem ... : `OCRQuality : (`  
Zeile 199: CLASS AdminAssetPackage ...: `StatusRestriction : MANDATORY (`  
Zeile 251: CLASS AssetItem ...: `Language : MANDATORY (`  
Zeile 307: CLASS GeometryOfInterest (`...: `GeomQuality : MANDATORY (  

**HINWEIS:** 
Zeile: 156 - 160: `MANDATORY CONSTRAINT
	  (NationalRelevance <> #prio1  
	   AND NationalRelevance <> #prio2
	   AND NationalRelevance <> #prio3)
	   OR DEFINED (TypeNationalRelevance);`
	   --> CONSTAINT anpassen auf Ref.

Zeile: 184: 184 - 185 : `MANDATORY CONSTRAINT
      OCR <> #true OR DEFINED (OCRQuality);`
	   --> CONSTAINT anpassen auf Ref.

**Comment by anjaamrein** [comment]
Codes hinzugefügt unter den Bezeichnungen: "LegalDoc", "NatRelCat", "OCRQuality", "StatusRestriction", "Language", "GeomQuality".

**Comment by anjaamrein** [comment]
Für jede Enumeration Zeile mit Referenz zu DMAssetsCatalogues.Catalogues.xxxxRef hinzugefügt. 
--> noch nicht kontrolliert, da ili2c nicht lief

**Comment by oesterli** [comment]
@anjaamrein 
Ich habe die beiden Modelle jetzt so korrigieren können, dass sie keine Fehler mehr im ili2c ergeben.
Wir können dann morgen mit dem aufteilen der Modelle beginnen.

Der aktuelle Branch work211117 habe ich auf https://github.com/oesterli/dmAssets/tree/work211117 gepushed.
