### ISSUE TITLE
ROI

### ISSUE THREAD

**Issue by oesterli** [oesterli/dmAssets#6]
Fortsetzung von Issue #3 

Ein Asset besitzt eine ROI, die beliebig viele Geometrietypen und Geometrien enthält.
Eine ROI hat besitzt das Attribut `Geom_Quality` mit dem angegeben wird wie genau die Geometrie erfasst wurde oder ob sie nur abgeschätzt wurde. Die gilt pro Multi-Geometrie-Objekt (Punkt, Linie, Fläche).

Ein Asset soll nur 0..1 ROI haben. 
Jeder AssetPart soll ebenfalls genau 0..1 ROI haben. Assets / AssetParts ohne ROI sind erlaubt

Ist ein Dokument-Link immer mit einer Geometrie verknüpft (über AssetPart bzw. Asset)?

**Comment by oesterli** [comment]
@signedav Du hast geschrieben:
"Ist ein Dokument-Link immer mit einer Geometrie verknüpft (über AssetPart bzw. Asset)?" 

Was bedeutet das?

**Comment by signedav** [comment]
Weiss nicht mehr auf was ich hinaus wollte 😊 Denke hat sich sowieso geklärt.

**Comment by signedav** [comment]
> Jeder AssetPart soll ebenfalls genau 0..1 ROI haben. Assets / AssetParts ohne ROI sind erlaubt

Das widerspricht sich. Entweder soll jeder Asset 1 ROI haben, oder Assets ohne ROI sind erlaubt.
Meinst du, ROI ohne Assets sind nicht erlaubt?

**Comment by signedav** [comment]
Übrigens noch eine Frage:
`Geom_Quality` und `Remark` ist pro `RegionOfInterest`, richtig? Nicht pro Geometrie der `RegionOfInterest`.
Das heisst also eine `Geom_Quality` pro `Asset`.

**Comment by oesterli** [comment]
> Übrigens noch eine Frage:
> 
> `Geom_Quality` und `Remark` ist pro `RegionOfInterest`, richtig? Nicht pro Geometrie der `RegionOfInterest`.
> 
> Das heisst also eine `Geom_Quality` pro `Asset`.
> 
> 

Geom_Quality wird doch vererbt. Deshalb hab ich es in der ROI modelliert, damit ich es nicht in jeder Geometrieklasse eintragen muss.

**Comment by signedav** [comment]
Ja das Stimmt. Dann hab ich es falsch verstanden. Also soll es in jeder Geometrie drin sein (genauso wie Remark), richtig?

**Comment by oesterli** [comment]
> Ja das Stimmt. Dann hab ich es falsch verstanden. Also soll es in jeder Geometrie drin sein (genauso wie Remark), richtig?

Ja, das stimmt meiner Meinung nach so. ROI ist ja eine abstrakte Klasse, von der gibt es keine Objekte ohne die Geometrie "Sub-"Klassen.

**Comment by oesterli** [comment]
> > Jeder AssetPart soll ebenfalls genau 0..1 ROI haben. Assets / AssetParts ohne ROI sind erlaubt
> 
> 
> 
> Das widerspricht sich. Entweder soll jeder Asset 1 ROI haben, oder Assets ohne ROI sind erlaubt.
> 
> Meinst du, ROI ohne Assets sind nicht erlaubt?
> 
> 

Jedes Asset /AssetPart hat keine oder nur eine ROI. 
ROI ohne Asset macht für mich keinen Sinn. Assets ohne ROI kann es aber durchaus geben.

**Comment by signedav** [comment]
Arg. Ich denke ich brauch eine Pause. Ich hab gelesen "Assets / AssetParts ohne ROI sind *nicht* erlaubt". Sorry, habs genau so verstanden, wie du es geschrieben hast. Alles klar.

**Comment by signedav** [comment]
Ich habs mir nun nochmals angeschaut.

Die aktuelle Modellierung bildet genau ab, was wir brauchen. Wir können pro Asset (bzw. AssetPackage) beliebig viele Geometrien erfassen, die nur zu diesem Asset (bzw. AssetPackage) gehören. Die Geometrien in den StudyArea, StudyLocation, StudySection sind Einzelgeometrien (oder auch Multigeometrien im Sinne von einer Geometrie, die mehrere Teile enthalten kann). Somit kann ein Remark und eine Geol_Quality pro erfasster Geometrie hinzugefügt werden.

Diese Modellierung allerdings bedingt, dass es quasi keine RegionOfInterest gibt (und nicht wie mündlich spezifiziert: "Ein Asset hat genau eine RegionOfInterest". Also werden die Geometrien im Asset "gebündelt". Meiner Meinung nach macht das Sinn. Ist das auch für dich so in Ordnung? 
Wenn ja, dann würde ich das so lassen. Einzig die Benennungen finde ich etwas verwirrend: Eine StudyArea, StudyLocation bzw. StudySection "ist" eine RegionOfInterest (und nicht Teil davon), deshalb würde ich RegionOfInterest in StudyGeometry oder GeometryOfInterest oder ähnlich umbenennen.

**Comment by signedav** [comment]
Falls du aber findest, dass eine RegionOfInterest die einzelnen Geometrien "bündeln" soll und eine 1 zu 1 Beziehung zu Asset (bzw. AssetPackage) haben soll, müssten wir dies ummodellieren.

```
        CLASS Asset =
            Name: TEXT;
        END Asset;

        CLASS GeometryOfInterest (ABSTRACT) =
            Geom_Quality : MANDATORY Geom_Quality;
            Remark : TEXT*20;
        END GeometryOfInterest; 

        CLASS StudySection EXTENDS GeometryOfInterest =
            Geometry : MultiLine;
        END StudySection;

        CLASS StudyArea EXTENDS GeometryOfInterest =
            Geometry : MultiSurface;
        END StudyArea;
        
        CLASS StudyLocation EXTENDS GeometryOfInterest =
            Geometry : MultiPoint;
        END StudyLocation;

        CLASS RegionOfInterest =

        END RegionOfInterest;

        ASSOCIATION RegionOfInterest_GeometryOfInterest =
            RegionOfInterest -- {1} RegionOfInterest;
            GeometryOfInterest -- {0..1} GeometryOfInterest;
        END RegionOfInterest_GeometryOfInterest;

        ASSOCIATION Asset_RegionOfInterest =
            Asset -- {1} Asset;
            RegionOfInterest -- {1} RegionOfInterest;
        END Asset_RegionOfInterest;
```

Ich denke aber nicht, dass das Sinn macht - es sei denn eine RegionOfInterest würde noch weitere Eigenschaften kriegen.

**Comment by signedav** [comment]
Anbei noch die eine Modellierung von Multi-Punkten, Multi-Linien und Multi-Polygonen:
```
    DOMAIN  
        Line = POLYLINE WITH (STRAIGHTS) VERTEX GeometryCHLV95_V1.Coord2;
        Surface = SURFACE WITH (STRAIGHTS) VERTEX GeometryCHLV95_V1.Coord2 WITHOUT OVERLAPS > 0.005;
        
        !! BAG OF with INTERLIS 2.3 only possible with STRUCTURE
        STRUCTURE PointStructure = 
            Point: GeometryCHLV95_V1.Coord2;
        END PointStructure;
        
        !!@ili2db.mapping=MultiPoint
        STRUCTURE MultiPoint =
            Points: BAG {1..*} OF PointStructure;
        END MultiPoint;
        
        STRUCTURE LineStructure = 
            Line: Line;
        END LineStructure;
        
        !!@ili2db.mapping=MultiLine
        STRUCTURE MultiLine =
            Lines: BAG {1..*} OF LineStructure;
        END MultiLine;
        
        STRUCTURE SurfaceStructure = 
            Surface: Surface;
        END SurfaceStructure;
        
        !!@ili2db.mapping=MultiSurface
        STRUCTURE MultiSurface =
            Surfaces: BAG {1..*} OF SurfaceStructure;
        END MultiSurface;

    TOPIC Assets =
[...]
        CLASS StudySection EXTENDS RegionOfInterest =
            Geometry : MultiLine;
        END StudySection;

        CLASS StudyArea EXTENDS RegionOfInterest =
            Geometry : MultiSurface;
        END StudyArea;
        
        CLASS StudyLocation EXTENDS RegionOfInterest =
            Geometry : MultiPoint;
        END StudyLocation;
[...]
    END Assets; !! of TOPIC
```

Pro Asset (und somit RegionOfInterst) würde man somit mehrere Multigeometrien der verschiedenen Typen erfassen. Beachte, dass die Attribute `Geom_Quality` und `Remark` pro Multigeometrie gelten. Dies macht Sinn, wenn man zum Beispiel eine Fläche hat mit mehreren Teilen, die voneinander getrennt sind. Dies soll als eine Multigeometrie gelten mit einem Remark. Eine andere Fläche, die zum selben Asset gehört aber nicht ein Teil der ersten ist, wäre dann eine zweite Multigeometrie mit eigenem Remark. Ist das so, wie du dir das vorgestellt hast? Ansonsten wärs auch kein Problem, wenn wir auf die Multigeometrien verzichten und ein Remark und eine Geom_Quality fix zu einem Punkt oder einem Polygonteil gehört. Allerdings ist es natürlich auch kein Problem Multigeometrien zu haben und dennoch immer nur einteilige Flächen oder einzelne Punkte zu erfassen, aber dennoch für die Zukunft gerüstet zu sein.

**Comment by oesterli** [comment]
Ja, ich glaube, dass wir jetzt auf dem richtigen weg sind.
Die ROI war für mich nur ein Konstrukt mehrere Geometrien mit verschiedenen geometrietypen abbilden zu können.
Es stimmt die Bezeichnung ROI ist verwirrend, ich finde gut, wenn wir die Klasse ROI in GeometryOfInterest umbenennen. Da es eine abstrakte Klasse ist, gibt es kein GeometryOfInterest-Objekt ohne eine spezielle Geometry. Damit sind folgende Situationen abbildbar:
Ein Asset / AssetPackage hat:
- **0** GeometryOfInterest.StudyLocation-Objekt (bzw. .StudySection- oder StudyArea-Objekt)
- **nur 1** GeometryOfInterest.StudyLocation-Objekt **oder** .StudySection-Objekt **oder** .StudyArea-Objekt
- **mehrere** GeometryOfInterest.StudyLocation-Objekte **oder** .StudySection-Objekte **oder** .StudyArea-Objekte
- **mehrere** GeometryOfInterest.StudyLocation-Objekte **und** .StudySection-Objeket **und** .StudyArea-Objekte

Ich werde einen neuen Branch erstellen und dort folgende Anpassungen machen
- Klasse `RegionOfIntereset` in `GeometryOfInterest` umgebenennen
- Die MultiGeometrie-Modellierung, wie Du in https://github.com/oesterli/dmAssets/issues/6#issuecomment-885731078 vorgeschlagen hast einfügen.

**Comment by signedav** [comment]
Können wir den schliessen?

**Comment by oesterli** [comment]
ja. mach ich
