### ISSUE TITLE
Publication Beziehungs Constraints

### ISSUE THREAD

**Issue by signedav** [oesterli/dmAssets#8]
Die Beziehung zwischen Publication und Asset bzw. AssetPackage soll mindestens ein Objekt der beiden Child-Klassen enthalten. Dies lässt sich nicht mit einem Constraint sicherstellen, da es ja eine n:m Beziehung ist und die Referenzen in der Beziehung liegen.

Es gäbe die Lösung eine Super-Klasse zu erstellen, diese zu Vererben und dann die Beziehung auf die Super-Klasse zu machen. Das sähe dann so aus: 

```
        CLASS AssetBase (ABSTRACT) =
        END AssetBase;

        CLASS AssetPackage EXTENDS AssetBase =
	    ID : TEXT*50;
        END AssetPackage;

        CLASS Asset EXTENDS AssetBase =
            Name: TEXT;
        END Asset;

        CLASS Publication =
            Date : MANDATORY FORMAT INTERLIS.XMLDate "1582-1-1" .. "2222-12-31";
        END Publication;

        ASSOCIATION AssetBase_Publication =
            AssetBase -- {1..*} AssetBase;
            Publication -- {0..*} Publication;
        END AssetBase_Publication;
```

**Comment by signedav** [comment]
@nOester Bitte sag mir, ob ich dies gleich im DM_Asset_210720.ili anpassen und einen PR machen soll oder ob du es dir selbst anschaust.

**Comment by oesterli** [comment]
@signedav 
Ich baue das in meinen Branch ein und pushe diesen auf github. Ich  mach dann einen PR und lad dich zum review ein.

**Comment by oesterli** [comment]
@signedav 
Ich habe eine PR erstellt. weiss aber nicht ob ich die korret als Reviewer eingeladen habe.

Noch eine Frage.
Wir haben jetzt die abstrakte Klasse `AssetBase` eingeführt und darüber die Beziehung der Sub-Klassen `Asset` und `AssetPackage` zur Klassse `Publication` modelliert. Würde das nicht auch für die Beziehung von `Asset` und `AssetPackage` zu den Klassen `Contact` und `AssetAdmin` Sinn machen? `Asset` und `AssetPackage` können mit diesen beiden Klassen in Beziehung stehen (für `AssetPackage` ist das bisher noch nicht modelliert).
Dann stellt sich für mich die Anschlussfrage. Könnte man nicht alles Attribute, die sowohl in `Asset` als auch in  `AssetPackage` vorliegen und die gleiche Bedeutung haben (z.B. Restriction) in die abstrakte Klasse `AssetBase` einfügen?

**Comment by signedav** [comment]
Ok. Davon ging ich bisher nicht aus. Aber ja. Sofern ein AssetPackage ebenfalls mit AssetAdmin und Contacts verknüpft ist, würde das Sinn machen.

Und eine Verknüpfung über AssetBase zur Geometrie würde sowieso Sinn machen.

Wenn es dann so gemacht wird können wir diesselben Attribute gut in AssetBase nehmen. Vielleicht macht dann wiederum eine Umbenennung Sinn. Aber das können wir machen, wenn wir sehen aus was dann die AssetBase genau besteht.

**Comment by signedav** [comment]
Und könnte man die Daten von AssetAdmin auch gleich ins AssetBase nehmen? Oder weshalb waren die nochmals vom Asset separiert? Rein thematisch?

**Comment by oesterli** [comment]
Die meisten Attribute gelten meiner Meinung nach für Asset und `AssetPackage`. Einige machen nur für `Asset `Sinn, z.B. `OCR`.
Könnte man das Problem denn mit einem `CONSTRAINT `abfangen, das man definiert, dass `OCR `für ausgefüllt werden soll, wenn man ein Objekt von `Asset `bearbeitet?

**Comment by signedav** [comment]
Man kann schon ein Constraint auf einer Vererbung `Asset` setzen, um ein existierendes Attribut `OCR` im Parent `AssetBase` genauer zu definieren. Allerdings stellt sich dann die Frage, weshalb `OCR` überhaupt im `AssetBase` ist. Vielleicht kannst du mal die Attribute aufteilen. Was wird von beiden verwendet und was nur von einem der beiden. Wenn es dann auch thematisch einigermassen Sinn macht, dann würde ich sagen, machen wirs so.

Was ist die Situation betreffend `AssetAdmin`? Kann das zusammengenommen werden mit `AssetBase`?

**Comment by oesterli** [comment]
Hier die Aufstellung welche Attribute in Asset und7oder AssetBase vorkommen
https://github.com/oesterli/dmAssets/wiki/Class-AssetAdmin

**Comment by oesterli** [comment]
Klassen Asset und AssetAdmin von AssetAdmin und AssetPackageAdmin vererben.
